### PR TITLE
Make block icons more specific to the blocks

### PR DESCRIPTION
**Pull request by kienstra**
**Request For Code Review**

Hi @miina,
Could you please review this pull request, which changes the block [icons](https://developer.wordpress.org/resource/dashicons/)? 

new-block-icons

### CODE REVIEW

**Comment by postphotos** [comment]
Oh, the palm tree is cute! Kinda want to travel now. 🥇 Nice work, @kienstra! Do you think we should give this to a designer, too, maybe @jwold or someone else at a future date?

**Comment by kienstra** [comment]
Thanks, @postphotos. It'd be nice to have a designer for the icons eventually.

**Review by miina — APPROVED** [review]
@kienstra Thank you for addressing this and changing the WordPress icons, looks good to me!

**Comment by jwold** [comment]
I think that's a great idea to play with the icons. These are good for now :)

Are we limited to dashicons, or can we use anything?

**Comment by miina** [comment]
Hey @jwold, we can use custom icons, too, not only dashicons.

**Pull request merged**
