### PR TITLE
[Gutenberg]: Integrate travel angles to hero

### PR DESCRIPTION
**Pull request by miina**
Moves travel angles to Hero block and removes Travel Angles block.

Also edits Gutenberg blocks style to make Hero, Featured Destinations, and Search block wide.

### CODE REVIEW

**Comment by ThierryA** [comment]
@kienstra I am merging this to be able to record the demo. It would be good has to be retro reviewed when time allows.

**Comment by kienstra** [comment]
**Thanks, Will Retro Review**

Hi @ThierryA,
That sounds good. I'll review this retroactively.

**Comment by kienstra** [comment]
Hi @miina,
The new "Hero" looks good. Thanks a lot for doing this so quickly. 

The only issue I saw was that it's possible to scroll horizontally past the block. But I might have missed a detail there.

possible-to-scroll-horizontally

**Comment by miina** [comment]
Hey @kienstra, thanks for noticing that, it looks like this issue was there already before. At least when I reversed the changes locally, it still appeared.

Created a PR that just hides the editor overflow, let me know if you know of a better solution for that, not sure if that's the correct way to go:
https://github.com/xwp/travel/pull/57

Thank you!

**Comment by kienstra** [comment]
**Thanks For The PR, That Fixed It**

Hi @miina,
Thanks a lot for the fix in #57. That closes the only remaining (small) issue here.

**Pull request merged**
